### ISSUE TITLE
Please add a license file and consider renaming the repository

### ISSUE THREAD

**Issue by unixorn** [odunlop/zsh-theme#1]
I'd like to add this to [awesome-zsh-plugins](https://github.com/unixorn/awesome-zsh-plugins), but I only add themes with a license file, some people won't use any code that doesn't have an open source license. If you don't have one in mind, https://choosealicense.com is a good resource to help you select an appropriate one.

The plugin's name is very generic. Please consider renaming it to something descriptive, or even just name it `even-more-emojis` after your the plugin file.

Finally, don't take these as criticisms of the work you've done, they're meant to make a more useful entry in the plugin/theme list.

Thanks!

**Comment by odunlop** [comment]
Updated the repo as per your recommendations! :)

**Comment by unixorn** [comment]
Adding it in today's update. Thank you.
